<?php
/*
 * SnowflakeAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SnowflakeAPILib\Tests;

use SnowflakeAPILib\APIException;
use SnowflakeAPILib\Exceptions;
use SnowflakeAPILib\APIHelper;
use SnowflakeAPILib\Models;

class APIControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \SnowflakeAPILib\Controllers\APIController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass()
    {
        $client = new \SnowflakeAPILib\SnowflakeAPIClient();
        self::$controller = $client->getClient();
    }

    /**
     * Setup test
     */
    protected function setUp()
    {
        $this->httpResponse = new HttpCallBackCatcher();
    }

    /**
     * Base on Twitter Snowflake algorithm.
     */
    public function testTestReturnsGeneratedID1()
    {

        // Set callback and perform API call
        $result = null;
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            $result = self::$controller->getIdGet();
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }
}
