<?php
/*
 * SnowflakeAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SnowflakeAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'http://10.110.0.25:18005';
}
