<?php
/*
 * SnowflakeAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SnowflakeAPILib;

use SnowflakeAPILib\Controllers;

/**
 * SnowflakeAPILib client class
 */
class SnowflakeAPIClient
{
    /**
     * Singleton access to API controller
     * @return Controllers\APIController The *Singleton* instance
     */
    public function getClient()
    {
        return Controllers\APIController::getInstance();
    }
}
